logging:
  level:
    star16m: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
application:
  scheduler:
    thread:
      name:
        prefix: SAMPLE_SCHEDULER_THREAD
    pool:
      size: 10