logging:
  level:
    star16m: DEBUG
spring:
  profiles:
    include: enabled-swagger
  # datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: mysecretpassword1234
  batch:
    # 초기 기동 시에 스키마 작성 여부
    initializer:
      enabled: false
    # 초기 기동 시에 배치 실행 여부
    job:
      enabled: false
    # 커스텀 chunk size
    chunksize: 100
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: false
application:
  # scheduler 설정
  scheduler:
    thread:
      name:
        prefix: SAMPLE_SCHEDULER_THREAD
    pool:
      size: 10
app:
  version: v0.1
mybatis:
  type-aliases-package: star16mstar16m.bootsample.core.resource.entity
  type-handlers-package: star16m.bootsample.web.common.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl